'use client';

import { usePathname, useRouter } from 'next/navigation';
import { useMemo } from 'react';

import MainPanel from '@/components/MainPanel';
import SubPanel from '@/components/SubPanel';
import Tab from '@/components/Tab';

import style from './layout.module.scss';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

const PageLayout = ({ children }: { children: React.ReactNode }) => {
  const router = useRouter();
  const pathName = usePathname();

  const onTabChange = (index: number) => {
    switch (index) {
      case 0:
        router.push('/sample/item');
        break;
      case 1:
        router.push('/sample/expense');
        break;
      case 2:
        router.push('/sample/memo');
        break;
      default:
        break;
    }
  };

  const tabIndex = useMemo(() => {
    switch (pathName) {
      case '/sample/item':
        return 0;
      case '/sample/expense':
        return 1;
      case '/sample/memo':
        return 2;
      default:
        return 0;
    }
  }, [pathName]);

  return (
    <div className={style['page-component']}>
      <div className={style['sub']}>
        <SubPanel />
      </div>
      <div className={style['main']}>
        <div className={style['tab']}>
          <Tab onChange={onTabChange} defaultIndex={tabIndex} />
        </div>
        <div className={style['panel']}>
          <MainPanel>{children}</MainPanel>
        </div>
      </div>
    </div>
  );
};

export default PageLayout;
