'use client';

import clsx from 'clsx';
import { useState } from 'react';

import IconTriangle from '@/components/presentations/Icon/IconTriangle';
import MainPanel from '@/components/presentations/MainPanel';
import SubPanel from '@/components/presentations/SubPanel';
import Tab from '@/components/presentations/Tab';
import { useResponsive } from '@/hooks/useResponsive';

import style from './layout.module.scss';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

const PageLayout = ({ children }: { children: React.ReactNode }) => {
  const [isOpen, setIsOpen] = useState<boolean>(false);
  const { isSp } = useResponsive();

  const onClick = () => {
    if (!isSp) return;
    setIsOpen(!isOpen);
  };

  return (
    <div className={style['page-component']}>
      <div className={clsx(style['sub'], isOpen && style['-open'])}>
        <SubPanel isOpen={isSp ? isOpen : true} />
        <span
          className={clsx(style['icon'], isOpen && style['-reverse'])}
          onClick={onClick}>
          <IconTriangle />
        </span>
      </div>
      <div className={style['main']}>
        <div className={style['tab']}>
          <Tab />
        </div>
        <div className={style['panel']}>
          <MainPanel>{children}</MainPanel>
        </div>
      </div>
    </div>
  );
};

export default PageLayout;
